[package]
name = "wave"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
circular-buffer = "1.0.0"
clap = { version = "4.5.28", features = ["derive"] }
csv = "1.3.1"
hound = "3.5.1"
indicatif = "0.17.9"
serde = { version = "1.0.217", features = ["derive"] }
